---
- hosts: 172.31.16.150 
  become: yes
  tasks:
  - name: i want to install git,tree and wget by using same task
    apt:
       name: "{{ item }}"
       state: present
    loop:
       - git
       - tree
       - wget
       